### ISSUE TITLE
Sapflow C9 and C18 have NA grid location in dashboard data

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#102]
😕

**Comment by bpbond** [comment]
They're NA in the `./Design/sapflow_inventory.csv` file.

**Comment by stephpenn1** [comment]
okay ill check those when i update inventory with Alice's tomorrow (Sunday)

**Comment by bpbond** [comment]
Note these now have entries in the sapflow inventory file, see #109 , but they're not correct; we need to fix based on actual locations of the two trees.

**Comment by bpbond** [comment]
C18 is by G1
C9 is by A2
