### ISSUE TITLE
Depth selector?

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#103]
Do you still want a depth selector for the maps @stephpenn1 ?

**Comment by stephpenn1** [comment]
yes just for teros

**Comment by bpbond** [comment]
OK, added in 3479f59:

<img width="969" alt="Screenshot 2023-06-03 at 1 07 48 PM" src="https://github.com/COMPASS-DOE/TEMPEST/assets/1956468/4cd5cca4-327a-44ad-9276-2862ff9bdb1b">

<img width="948" alt="Screenshot 2023-06-03 at 1 08 02 PM" src="https://github.com/COMPASS-DOE/TEMPEST/assets/1956468/1b6a2b25-4889-4a46-8ac1-37a5c204c990">
