### ISSUE TITLE
FAGR inventory tags

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#11]
Beeches are hungry by nature and like to eat up tags, some (e.g. tag 1829) are hammered in too close and need to be pulled out a bit.. let's do this when we do 2021 inventory

**Comment by stephpenn1** [comment]
### Also when we do inventory:
- check species of F12 (1563) it seems to be incorrectly labeled on our sheets

**Comment by stephpenn1** [comment]
@bpbond For Tuesday, can you grab the inventory nails and tags and also the blue roll of sapflow tree putty in 1207 for @aestearns01

Alice, we will go around and pull out the nails in the Beeches during our inventory so you can take that off your to do list. However we will leave some spare nails and the putty in the PNNL cabinet

**Comment by bpbond** [comment]
Will do @stephpenn1

**Comment by aestearns01** [comment]
Thanks Stephanie! I noticed that there is currently a roll of putty in the
tool bag in the PNNL cabinet, but it couldn't hurt to have more.
