### ISSUE TITLE
Missing sapflow in inventory

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#25]
- C9
~- C11~
~- F13~

Needs to be IDed in the field and updated in `inventory.csv`

**Comment by stephpenn1** [comment]
C9 doesn't have a tag and is technically out of plot but i suspect its 1451

**Comment by stephpenn1** [comment]
@bpbond can you please check for Tag 1451 in the Control plot and see if that is C9? We are missing C9 in the inventory sheet and I suspect it is 1451, but not sure

**Comment by bpbond** [comment]
Also - I found 1829, which had tree tag secured by flagging, and re-mounted the tag. Can you add this in inventory file notes please? Thanks.

**Comment by bpbond** [comment]
Ok C9 now has tag 1456. It is out of plot, ACRU, 24.0 cm dbh.
