### ISSUE TITLE
New Years Repo Tidying

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#3]
- [x] `/Soil Transplant Experiment` should prob stay at https://github.com/PNNL-PREMIS/PREMIS-ghg for any further analysis and ms writing so we can track history
- [x] Resolve diff between @bpbond's TEMPESTX and the one here
- [x] Do we still want the `TEMPESTX` folder to be separate from the `Data` folder?
- [x] Remove spaces in data file names for comp readability

**Comment by stephpenn1** [comment]
Confused why I cant assign myself this??

**Comment by bpbond** [comment]
🤷‍♂️ 😕
