### ISSUE TITLE
Licor analyzers

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#32]
From call with Kristen Minish.

* Loaner of 7820 (N2O) + new multiplexer + hopefully 4 LTCs
* Plumb desiccant inline before flooding
* Can mount analyzers on shipping pallets, cinderblocks, etc.
* Trace gas analyzers (and power supplies) are not weatherized (unlike multiplexer)
* Licor uses a doghouse to protect them!
* Methane analyzer - the two vents are not weatherized - they need 1-2" clearance to cool instrument
* Licor website has options for weather traps - https://licor.com/env/support//LI-7810/topics/avoiding-water-ingress.html
* Take a hard look for any condensation in lines from LTC -> multiplexer -> analyzer
* Definitely can loan analyzer, she will check about multiplexer & let know within a week or two
* Have analyzer to us by beginning of June (maybe sooner)

![image](https://user-images.githubusercontent.com/1956468/113722933-debfda80-96be-11eb-8dc0-5b585cb3b0bf.png)

**Comment by bpbond** [comment]
>We should track instrument serial numbers for TEMPEST

>Maybe we have a “licor_installation.csv” file that has date, plot, nickname, serial number

**Comment by stephpenn1** [comment]
Closing because test event and loaners are done :)
