### ISSUE TITLE
Inventory needs to record grid square!

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#33]

**Comment by bpbond** [comment]
Also:

* Would we like to add a stressed/declining flag to the inventory?
* Inventory frequency wrt tree stress and mortality—rethink
* Check README metadata

**Comment by bpbond** [comment]
@stephpenn1 I am totally into doing this (grid square recording). It would enable SUCH COOL VISUALIZATIONS.

**Comment by stephpenn1** [comment]
Resolved by PR #34 ?

**Comment by bpbond** [comment]
Yes.
