### ISSUE TITLE
SP Rest of April

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#35]
@bpbond please add / edit anything you'd like

#### TEMPEST - data
- [x] Develop plan for the data processing of each data stream (including an inventory of what scrips have already been written)
- [x] Check sapflow values now that leaves are out
- [ ] Update READMEs

#### TEMPEST - field
- [x] think / talk about licor downloading schedule

#### Syntheses 
- [x] ~bring in [2018+](https://docs.google.com/spreadsheets/d/1n98yh99GqvutF4h8O1LzC8vYTfwezK9Dp4JIqXugRk0/edit#gid=0) studies and integrate into the Rmd~ moved to #36

**Comment by bpbond** [comment]
Sounds good SP—thank you.

**Comment by bpbond** [comment]
Tuesday 4/27

- O.o.o. notifying 
- Interns
- Anya meeting
- TEMPEST scripting 
- Data synthesis

**Comment by bpbond** [comment]
Monday 5/3

* Week plans? Please create a new issue
* Specific next steps for data processing? Progress?
* Meta-analysis - incorporating 2018-2020 data into script
* IRGA checking and downloading - how to handle
* Other?
