### ISSUE TITLE
SP Week of May 3rd 

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#36]
- [x] Create design plan for TEMPEST pipeline
- [x] Take inventory of where data processing is / lives for TEROS, Licor, sapflow, wells, and tree inventory
- [x] bring in [2018+](https://docs.google.com/spreadsheets/d/1n98yh99GqvutF4h8O1LzC8vYTfwezK9Dp4JIqXugRk0/edit#gid=0) studies and integrate into the Rmd
- [x] SP to make log sheet for Licors measurement/checking/downloading and run by Anya
- [x] BBL to circle back with Roy
- [x] Check if Roy can meet at GCREW Tuesday for sapflow sensors
- [x] Create skeleton Rmd for sapflow and use the last dropbox file

**Comment by bpbond** [comment]
I think you said you'll also tackle integrating 2018-2020 data into the meta-analysis repo and script? 🙏

**Comment by stephpenn1** [comment]
Yes though that's on the agenda for this week :-)

**Comment by bpbond** [comment]
Monday 5/3

* Week plans? Please create a new issue
* Specific next steps for data processing? Progress?
* Meta-analysis - incorporating 2018-2020 data into script
* Interns - BBL update
* IRGA checking and downloading - how to handle
* Other?
