### ISSUE TITLE
SP Week of May 24

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#39]
### Pipeline
- [x] Create a test dataset with a few bad days and a few good days of sapflow data
- [x] Check test dataset for weird days (daytime values > nighttime values; midnight to 6 should look like 6 to midnight)
- [x] Check for weird hours (does 10am match up with +- 3 days; does that meas fall btw previous and next measurement)
- [ ] Set up meeting with Nate next week to discuss these and other metrics

**Comment by bpbond** [comment]
I'm a little concerned that isn't clear enough and doesn't prioritize...consider something like this instead?

- [ ] Create a small test dataset with (1) a few normal days of sapflow data, (2) a few OK sensor but no leaves data, and (3) known bad sensor data
- [ ] Write a function: given 24 (or whatever) consecutive values, are middle 50% (roughly 6 AM - 6 PM) higher than others? Returns TRUE or FALSE
- [ ] Test function on test data and visualize 
- [ ] Set up meeting with Nate next week to discuss these and other metrics

Bonus, if above done:
- [ ] Check for weird hours (does 10am match up with +- 3 days; does that meas fall btw previous and next measurement)
