### ISSUE TITLE
Field Work Jan - Mar 2021

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#4]
### goal 1: improve & check sapflow insulation 
- [x] update tree covers with improved design
- [x] new labeling and putty on insulation covers
- [x] power is on at each loggerbox, but would like to check individual sensors
- [x] talk to Roy about battery in the fresh plot

### goal 2: troubleshoot continuous licor power issue
- [x] remove IRGAs from field
- [x] check fuses
- [x] test on line power
- [x] talk to licor about power draw of IRGA + multiplexer in context of current power usage in the plots

### goal 3: getting litter under control
- [x] develop a plan for sorting litter
- [ ] talk to Nate and others about what is important to capture and at what time scale

### goal 4: new instrument learning
- [x] read 2200C manual
- [x] test out instrument and be able to understand general usage

**Comment by stephpenn1** [comment]
@bpbond can you grab a power supply cable from 1207 for the AC to DC power adapter? See specs below...

- Part Number 9981-140 Power Supply Cable
- 4 pin (F-F) 2m

My guess is it's either yellow like the photo below or grey.

### From the manual: 
> The AC to DC power supply includes a 2 m power cord that connects the power supply to the LI-8150 Multiplexer (part number 9981-140). Connect the power cord between the power supply and multiplexer before plugging the power supply into a power outlet.

![image](https://user-images.githubusercontent.com/20341158/104377065-e32b8b80-54f3-11eb-9c3a-5c68ca267f25.png)

**Comment by stephpenn1** [comment]
**Note to talk to licor about:** When I pulled out a longterm chamber from the salt plot, the inside of the chamber was covered in sandy soil sensors included. I assume the LT chambers are built for extended outdoor use... but I'm concerned it could be harmful to the measurement. 

<img width="828" alt="Screen Shot 2021-01-14 at 12 56 10 PM" src="https://user-images.githubusercontent.com/20341158/104629744-e21b6b00-5667-11eb-9c75-8f28600098e8.png">

**Comment by bpbond** [comment]
Ok, Norbert is started for test. It's measuring every two hours, started 1:05 PM today, logging to internal flash ￼(almost no free space on either flash card).
