### ISSUE TITLE
Update field laptop

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#45]
@stephpenn1 can you take WE34259 and put it onto the PNNL network, or take it into the office if needed, and work with Sean to get any needed updates applied? Right now it's saying that Windows needs to be activated. Assigning this to you as you're the primary (official) user. Thanks.

**Comment by bpbond** [comment]
I will set up milestones and use those to assign due dates, if that works.

**Comment by bpbond** [comment]
@stephpenn1 I left your laptop in 1207 with two SIM cards on top of it: from Norbert (in TEMPEST control currently) and the unit currently in 1207 (I think [Stuart](https://www.getbeautified.com/minion-names/#18_Stuart_8211_Minion_Names)). Can you download anything on these cards and reformat them as part of updating the laptop? Thank you

**Comment by stephpenn1** [comment]
Yup thanks!

**Comment by stephpenn1** [comment]
Laptop is updated and was put on the pnnl network, dropped back off at GCReW in the top shelf of the PNNL cabinet

**Comment by bpbond** [comment]
Hallelujah—thanks! I've been getting so tired of the warning messages :)
