### ISSUE TITLE
Download and clean up (reformat) all CF cards and reinstall into Licors

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#47]

**Comment by stephpenn1** [comment]
Everything is downloaded and cleared. I sent the files to myself to sort through and upload if needed. Norbert's CF was put back in the licor and run. The other is still in the CF reader on the top shelf of the PNNL cabinet (I think, if not then I put it back in Stuart)

**Comment by bpbond** [comment]
Thank you @stephpenn1
