### ISSUE TITLE
TEROS QA/QC

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#50]
If we like the basic form of sapflux QA/QC ( #49 ), develop similar document for TEROS Current_data:
* Create RMarkdown
* Get feedback from A&A, @bpbond

**Comment by bpbond** [comment]
We decided (meeting today) that this would be up next for SP.

**Comment by stephpenn1** [comment]
From 6/16 meeting:
- basic qa / qc is okay for tests
- some sort of spatial comparison of neighboring sensors (stats per grid cell? graphs per grid cell?)
- comparison graph by depth: useful when we flood

**Comment by stephpenn1** [comment]
7/8 meeting with AS and EP:
- [ ] check manual for data ranges
- [ ] last online date would be useful
- [ ] if last online date != today, how many days of NAs did we have
