### ISSUE TITLE
SP Week of June 8

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPEST#51]
@stephpenn1 can you keep creating these weekly issues please? It's a good check that we're on the same page in terms of to-dos and priorities. Thanks.

**Comment by stephpenn1** [comment]
- [ ] Request day to bring laptop to office (#45), talk with BBL on best days
- [ ] Set up meeting with Anya and Alice to go over sapflow document
- [ ] Create TEROS qa / qc doc structure (#50)
