### ISSUE TITLE
SP Week of Jun 21

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#55]
### ESS-DIVE
- [x] finish up remaining ESS-DIVE reporting format tasks (remaining github issues)
- [x] meet with Charu and Rob to do a final walkthrough

### TEMPEST
- [x] look over Anya's manuscript
- [ ] read meta regression document
- [ ] #50  (more details after Monday meeting)
- [ ] finishing touches on #49 (more details after Monday meeting)
- [x] finish sample ID slides with Anya

**Comment by bpbond** [comment]
Thanks for the productive meeting today @stephpenn1  🙂
