### ISSUE TITLE
SP Week of 6/28

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#58]
- [x] Finish #49 
- [x] Merge current PR #57 
- [x] Add install date to summary table
- [x] Add graph of deeper sensors and send to Alice
- [x] Create spatial map using grid column (is Alice doing this?)
- [ ] Run it by A^2
- [x] Open PR for `pipelines` into `master` on sapflow script
- [ ] Finish #50 
- [x] To fill in

... more following meeting

**Comment by stephpenn1** [comment]
Hi @bpbond I am behind on this task list because of the busy-ness of last week. I will be finishing the sapflow tasks today and the teros process step and would like to meet tomorrow if possible to go over everything.

**Comment by bpbond** [comment]
@stephpenn1 Ah, funny, I was just coming here to check this list. OK, sounds good, thank you. Could you also update our "SCP task overview" google sheet please?

Tomorrow...hmm, I won't have much time. If we meet with Adam at 9, maybe you and I could touch base immediately after—would that work?
