### ISSUE TITLE
To Do before Test Event

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#66]
- [x] Contact Licor and explain our upcoming irrigation test; we assume we want dessicant on-hand for the 7810 but
- Will the smart chamber + 7810 be ok in inundated water (with raised collars)? 
- Explain spot sampling with 7810 and automated measurements with 8100 + 8150
- any other maintenance for automated systems prior to event
Video link to change 7810 desiccant: [click here!](https://www.licor.com/env/support/LI-7810/videos/replacing-the-desiccant.html?CountryCode=COG)
- [x] Guest housing available at SERC?
- [x] Are we doing full sampling for seawater test?
- [x] System monitoring, what does this exactly mean?
- [x] Download all Licors, wipe CF

### Week of Aug 16:
- [x] Download and check on Kevin (Fresh plot)
- [x] Download and check on Stuart (Control)
- [x] Download and check on loaner setup (Salt)
- [x] (Hopefully) get doghouses in and installed
- [x] Place caps on open ports
- [x] Pallet in Fresh plot
- [x] Empty litter traps

SCP and BBL will definitely be there on Friday

**Comment by bpbond** [comment]
- Doghouses
- Pallets
