### ISSUE TITLE
SP week of 9th

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#69]
### Shiny Dashboard
- [x] script A: code from dropbox, processing, writes a `sapflow.csv` file
- straight from Rmd
- [x] shiny app reads file and displays
- [x] Dashboard: last 10 values
- [x] Charts: last 3 days viz
- [x] Update button in shiny that triggers script A

### Test Event Prep 
- [x] read manual on maintenance 
- [x] gather supplies for SERC tomorrow
- [x] check on guest housing
- [x] test licors up and running
- [ ] ~external battery on hand~

**Comment by bpbond** [comment]
Good list. If you want to have a follow-up in terms of design or performance, lmk.
